language: perl
matrix:
  include:
    - perl: "5.30"
      dist: xenial
    - perl: "5.28"
      dist: xenial
    - perl: "5.22"
      dist: xenial
      env: USE_SYSTEM_PERL=1
    - perl: "5.20"
      dist: precise
    - perl: "5.18"
      dist: precise
    - perl: "5.16"
      dist: precise
    - perl: "5.14"
      dist: precise
    - perl: "5.12"
      dist: precise
    - perl: "5.10"
      dist: precise
    - perl: "5.8"
      dist: precise

before_install:
 # Remove broken deb repo:
 - '[ "`lsb_release -cs`" = "precise" ] && sudo rm -f /etc/apt/sources.list.d/mongodb.list || true'
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb twm libx11-dev libfreetype6-dev libxft-dev
 - if [ "$USE_SYSTEM_PERL" = 1 ]; then perlbrew off; sudo apt-get install -qq perl-tk; fi
 - Xvfb :123 &
 - export DISPLAY=:123
 # Wait until X server is available
 - perl -MIO::Socket::INET -e 'for (1..10) { IO::Socket::INET->new(PeerAddr => "localhost:6123") and exit; sleep 1 }'
 - twm &
 # Wait until window manager is running
 - sleep 2

script:
 - perl Makefile.PL && env HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest

after_script:
 - make distcheck

sudo: true

branches:
 except:
  - /appveyor/
